[project]
name = "datalibrary-pipeline"
version = "2.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "brotli==1.1.0",
    "certifi==2024.2.2",
    "charset-normalizer==3.3.2",
    "greenlet>=3.1",
    "idna==3.7",
    "numpy>=2.0.0",
    "pandas>=2.2",
    "pip==24.0",
    "pyodbc>=5.2",
    "pysocks==1.7.1",
    "python-dateutil==2.9.0",
    "python-dotenv==1.0.1",
    "pytz==2024.1",
    "requests==2.32.2",
    "setuptools==70.0.0",
    "six==1.16.0",
    "sqlalchemy>=2.0",
    "tzdata==2024.1",
    "urllib3",
    "wheel==0.43.0",
    "win-inet-pton==1.1.0",
    "data-bridges-client",
    "data-bridges-knots",
]


[dependency-groups]
dev = [
    "black>=26.5.1",
    "isort>=8.0.1",
    "pytest>=9.0.3",
    "python-dotenv>=1.0.1",
    "ruff>=0.15.15",
]


[[tool.uv.index]]
name = "wfp-private"
url = "https://d2i4vvypvg40rv.cloudfront.net/pypi/"
explicit = true

[tool.uv.sources]
data-bridges-knots = { index = "wfp-private" }
data-bridges-client = { index = "wfp-private" }